import { relations } from 'drizzle-orm';
import {
  pgEnum,
  pgTable,
  text,
  integer,
  timestamp,
  index,
  unique,
} from 'drizzle-orm/pg-core';

import { user } from '@/server/db/auth-schema';

/**
 * App data schema: trips, their participants, expenses, expense splits, and
 * settlements. This is separate from auth-schema.ts (which is generated by
 * `npm run auth:schema` and must not be hand-edited) but lives in the same
 * Neon Postgres database, via the same Drizzle client - one backend, no
 * second database.
 *
 * IDs are `text` primary keys, generated as UUIDs (see
 * src/server/db/id.ts), not serial integers. This matters for the offline
 * -first sync design: a device creates a record locally while offline with
 * its own UUID, then syncs it to the server later. A serial/auto-increment
 * ID can't be known until the server assigns it, which forces awkward
 * client-side ID remapping after every sync. A client-generated UUID stays
 * the record's permanent ID before, during, and after sync.
 *
 * Soft deletes: `deletedAt` (nullable) instead of actually deleting rows.
 * An offline client can't tell "this ID never existed" apart from "this ID
 * existed and was deleted while I was offline" unless deletions are
 * recorded as rows, not row *removals*. Hard deletes lose that signal.
 */

export const expenseCategoryEnum = pgEnum('expense_category', [
  'food',
  'transport',
  'stay',
  'ticket',
  'other',
]);

export const trip = pgTable(
  'trip',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    currency: text('currency').default('INR').notNull(),
    budget: integer('budget'),
    startDate: timestamp('start_date'),
    endDate: timestamp('end_date'),
    coverImageUrl: text('cover_image_url'),
    createdBy: text('created_by')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
    deletedAt: timestamp('deleted_at'),
  },
  (table) => [index('trip_createdBy_idx').on(table.createdBy)],
);

export const tripParticipant = pgTable(
  'trip_participant',
  {
    id: text('id').primaryKey(),
    tripId: text('trip_id')
      .notNull()
      .references(() => trip.id, { onDelete: 'cascade' }),
    /**
     * Nullable: a participant doesn't need a TripExpense account (common
     * Splitwise-style pattern - you can add "Rohan" to a trip and track his
     * share without him ever signing up). When he does sign up and gets
     * linked, this is set and `displayName`/`avatarUrl` can fall back to
     * his account's own name/image.
     */
    userId: text('user_id').references(() => user.id, { onDelete: 'set null' }),
    displayName: text('display_name').notNull(),
    avatarUrl: text('avatar_url'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    deletedAt: timestamp('deleted_at'),
  },
  (table) => [
    index('trip_participant_tripId_idx').on(table.tripId),
    index('trip_participant_userId_idx').on(table.userId),
    // Postgres treats NULLs as distinct for uniqueness, so this only
    // prevents the same registered user being added to a trip twice - it
    // does not limit how many un-linked (userId IS NULL) participants a
    // trip can have.
    unique('trip_participant_trip_user_unique').on(table.tripId, table.userId),
  ],
);

export const expense = pgTable(
  'expense',
  {
    id: text('id').primaryKey(),
    tripId: text('trip_id')
      .notNull()
      .references(() => trip.id, { onDelete: 'cascade' }),
    title: text('title').notNull(),
    amount: integer('amount').notNull(),
    category: expenseCategoryEnum('category').notNull(),
    paidByParticipantId: text('paid_by_participant_id')
      .notNull()
      .references(() => tripParticipant.id, { onDelete: 'restrict' }),
    dateTime: timestamp('date_time').notNull(),
    note: text('note'),
    receiptUrl: text('receipt_url'),
    createdBy: text('created_by')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
    deletedAt: timestamp('deleted_at'),
  },
  (table) => [
    index('expense_tripId_idx').on(table.tripId),
    index('expense_paidByParticipantId_idx').on(table.paidByParticipantId),
  ],
);

export const expenseSplit = pgTable(
  'expense_split',
  {
    id: text('id').primaryKey(),
    expenseId: text('expense_id')
      .notNull()
      .references(() => expense.id, { onDelete: 'cascade' }),
    participantId: text('participant_id')
      .notNull()
      .references(() => tripParticipant.id, { onDelete: 'restrict' }),
    /**
     * Each participant's share of the expense. Stored explicitly (rather
     * than always deriving amount / splitBetween.length) so an uneven
     * split can be introduced later without a schema change - today's
     * client always writes an even split, but the column doesn't assume
     * that.
     */
    shareAmount: integer('share_amount').notNull(),
  },
  (table) => [
    index('expense_split_expenseId_idx').on(table.expenseId),
    unique('expense_split_expense_participant_unique').on(table.expenseId, table.participantId),
  ],
);

export const settlement = pgTable(
  'settlement',
  {
    id: text('id').primaryKey(),
    tripId: text('trip_id')
      .notNull()
      .references(() => trip.id, { onDelete: 'cascade' }),
    fromParticipantId: text('from_participant_id')
      .notNull()
      .references(() => tripParticipant.id, { onDelete: 'restrict' }),
    toParticipantId: text('to_participant_id')
      .notNull()
      .references(() => tripParticipant.id, { onDelete: 'restrict' }),
    amount: integer('amount').notNull(),
    settledAt: timestamp('settled_at').defaultNow().notNull(),
    createdBy: text('created_by')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at').defaultNow().notNull(),
  },
  (table) => [index('settlement_tripId_idx').on(table.tripId)],
);

export const tripRelations = relations(trip, ({ many }) => ({
  participants: many(tripParticipant),
  expenses: many(expense),
  settlements: many(settlement),
}));

export const tripParticipantRelations = relations(tripParticipant, ({ one, many }) => ({
  trip: one(trip, { fields: [tripParticipant.tripId], references: [trip.id] }),
  user: one(user, { fields: [tripParticipant.userId], references: [user.id] }),
  expensesPaid: many(expense),
  splits: many(expenseSplit),
}));

export const expenseRelations = relations(expense, ({ one, many }) => ({
  trip: one(trip, { fields: [expense.tripId], references: [trip.id] }),
  paidBy: one(tripParticipant, {
    fields: [expense.paidByParticipantId],
    references: [tripParticipant.id],
  }),
  splits: many(expenseSplit),
}));

export const expenseSplitRelations = relations(expenseSplit, ({ one }) => ({
  expense: one(expense, { fields: [expenseSplit.expenseId], references: [expense.id] }),
  participant: one(tripParticipant, {
    fields: [expenseSplit.participantId],
    references: [tripParticipant.id],
  }),
}));

export const settlementRelations = relations(settlement, ({ one }) => ({
  trip: one(trip, { fields: [settlement.tripId], references: [trip.id] }),
  from: one(tripParticipant, {
    fields: [settlement.fromParticipantId],
    references: [tripParticipant.id],
  }),
  to: one(tripParticipant, {
    fields: [settlement.toParticipantId],
    references: [tripParticipant.id],
  }),
}));
